name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      - name: Build Docker image
        run: docker build -t workoutapi .


      - name: Run container for tests
        run: docker run -d -p 8000:8000 --name testcontainer workoutapi


      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -s -f http://localhost:8000/ >/dev/null; then
              echo "API up!"
              break
            fi
            echo "Waiting... ($i/20)"
            sleep 2
          done


      - name: Debug response
        if: always()
        run: curl -v http://localhost:8000 || true


      - name: Run Python tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
          pytest tests


      - name: Test API endpoint
        run: curl --fail http://localhost:8000/api/workouts



      - name: Stop container
        if: always()
        run: docker stop testcontainer


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Tag Docker image
        run: |
          docker tag workoutapi patricialundholm1/workoutapi:latest
          docker tag workoutapi patricialundholm1/workoutapi:${{ github.sha }}


      - name: Push Docker image
        run: |
          docker push patricialundholm1/workoutapi:latest
          docker push patricialundholm1/workoutapi:${{ github.sha }}
